#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_TOMCAT7_IP:8080
sed -i "s/OPENSHIFT_TOMCAT7_IP/$OPENSHIFT_TOMCAT7_IP/g" $OPENSHIFT_REPO_DIR/tomcat/conf/server.xml
$OPENSHIFT_REPO_DIR/tomcat/bin/startup.sh &

