#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

# The logic to stop your application should be put in this script.
if [ -z "$(ps -ef | grep java | grep -v grep)" ]
then
    client_result "Application is already stopped"
else
	$OPENSHIFT_REPO_DIR/tomcat/bin/shutdown.sh	
#    kill `ps -ef | grep testrubyserver.rb | grep v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi
